### ISSUE TITLE
Add options for -n and -d to Linbo Sync plugin

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#171]
It would be nice to have the options `-n` and `-d` available in the Linbo sync plugin.
- n prevents the autostart
- d disabled the new gui

**Comment by kiarn** [comment]
Hello @CodeCrafter912 

I think it's done, it would be nice to test it if you can, but the displayed result command seems ok.

Arnaud

**Comment by dorianim** [comment]
Thank you,  I'll test it tomorrow :)

**Comment by dorianim** [comment]
Unfortunately I am unable to test this due to a bootstrap error. The browser console give the following logs:
```
[$injector:modulerr] Failed to instantiate module lmn.vdi_dashboard due to:
[$injector:nomod] Module 'lmn.vdi_dashboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by kiarn** [comment]
I'm not the author of the vdi plugin. Is there something in `/var/log/ajenti/*log` ?

**Comment by dorianim** [comment]
Yes, the logs shows an error as well:
```
2021-04-07 13:53:04,098 INFO    : Loading config from /etc/ajenti/config.yml
2021-04-07 13:53:04,101 INFO    : Loading users from /etc/ajenti/users.yml
2021-04-07 13:53:04,102 INFO    : Ajenti Core 2.1.40
2021-04-07 13:53:04,102 INFO    : Master PID - 5624
2021-04-07 13:53:04,102 INFO    : Detected platform: debian / Ubuntu 18.04.5 LTS
2021-04-07 13:53:04,102 INFO    : Python version: 3.6.9
2021-04-07 13:53:04,163 INFO    : Discovered 32 plugins
2021-04-07 13:53:04,197 INFO    : lmn_crontab.__init__.py: lmn_crontab loaded
2021-04-07 13:53:04,198 INFO    : docker.__init__.py: docker loaded
2021-04-07 13:53:04,199 ERROR   : [lmn_permissions]: plugin import failed: cannot import name 'ItemProvider'
2021-04-07 13:53:04,199 ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/plugins.py", line 337, in load_all_from
    self.__import_plugin_module(name, self[name])
  File "/usr/local/lib/python3.6/dist-packages/aj/plugins.py", line 361, in __import_plugin_module
    *imp.find_module(module_name, [module_path])
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/linuxmuster-webui/plugins/lmn_permissions/__init__.py", line 1, in <module>
    from .main import ItemProvider
ImportError: cannot import name 'ItemProvider'

2021-04-07 13:53:04,262 INFO    : lmn_nextcloud.__init__.py: lmn_nextcloud loaded
2021-04-07 13:53:04,273 INFO    : lmn_vdi_dashboard.__init__.py: lmn_vdi_dashboard loaded
2021-04-07 13:53:04,274 INFO    : lmn_vdi_administration.__init__.py: lmn_vdi_administration loaded
2021-04-07 13:53:04,275 INFO    : lmn_links.__init__.py: lmn_links loaded
2021-04-07 13:53:04,276 INFO    : samba_dns.__init__.py: samba_dns loaded
2021-04-07 13:53:04,280 INFO    : lmn_websession.__init__.py: lmn_websession loaded
2021-04-07 13:53:04,312 INFO    : lmn_dhcp.__init__.py: lmn_dhcp loaded
2021-04-07 13:53:04,313 INFO    : lmn_landing.__init__.py: lmn_landing loaded
2021-04-07 13:53:04,316 INFO    : Loaded 31 plugins
2021-04-07 13:53:04,317 INFO    : Binding to [0.0.0.0]:443
2021-04-07 13:53:04,323 INFO    : SSL enabled
2021-04-07 13:53:04,327 INFO    : New worker "restricted session" PID 5633, EUID 0, EGID 0
2021-04-07 13:53:04,327 INFO    : Worker 5633 is demoting to UID 65534 / GID 65534...
2021-04-07 13:53:04,328 INFO    : ...done, new EUID 65534 EGID 65534

```

**Comment by kiarn** [comment]
I have corrected this here : https://github.com/linuxmuster/linuxmuster-webui7/commit/452545b3057232b31d57ed75a9fcc47d52a67aaf
But I don't think it's related.

Maybe your error occurs because I have renamed all plugins and I forgot something in Angularjs, but I cannot reproduce this. Does the web console say something else ?

**Comment by dorianim** [comment]
Yes, it is unrelated.
The browser console shows 
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app__1617957693205 due to:
[$injector:modulerr] Failed to instantiate module lmn.vdi_dashboard due to:
[$injector:nomod] Module 'lmn.vdi_dashboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
very often together with 
`Angular bootstrap has failed`.

**Comment by kiarn** [comment]
Please try this : 

```
/usr/local/bin/ajenti-panel --dev --stock-plugins --plugins /usr/lib/linuxmuster-webui/plugins
```

There was some syntax change in the `plugin.yml`, and some plugins (ni_*) have not been updated yet. That's the reason why I didn't upload a deb package last week.

**Comment by kiarn** [comment]
In order to see what happen : 

```
ls /usr/lib/linuxmuster-webui/plugins
```

**Comment by dorianim** [comment]
I don't  see error when running the command you gave, but the bootstrap issue remains...
```
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
09.04.2021 18:21  [...     1230]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
09.04.2021 18:21  [...     1230]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
09.04.2021 18:21  [...     1230]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
09.04.2021 18:21  [...     1230]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
09.04.2021 18:21  [master  1230]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
09.04.2021 18:21  [master  1230]          core.py:76    INFO   Loading users from /etc/ajenti/users.yml
09.04.2021 18:21  [master  1230]          core.py:81    WARN   Debug mode
09.04.2021 18:21  [master  1230]          core.py:83    WARN   Dev mode
09.04.2021 18:21  [master  1230]          core.py:94    INFO   Ajenti Core 2.1.40
09.04.2021 18:21  [master  1230]          core.py:95    INFO   Master PID - 1230
09.04.2021 18:21  [master  1230]          core.py:96    INFO   Detected platform: debian / Ubuntu 18.04.5 LTS
09.04.2021 18:21  [master  1230]          core.py:97    INFO   Python version: 3.6.9
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.6
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.6/lib-dynload
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /root/.local/lib/python3.6/site-packages
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/linuxmuster
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/linuxmuster/setup.d
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python3.6/dist-packages
09.04.2021 18:21  [master  1230]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3/dist-packages
09.04.2021 18:21  [master  1230]       plugins.py:285   INFO   Discovered 32 plugins
09.04.2021 18:21  [master  1230]       plugins.py:333   DEBUG  Resolved load order for 32 plugins: ['core', 'lmn_cron', 'lmn_docker', 'lmn_permissions', 'lmn_setup_wizard', 'ace', 'plugins', 'dashboard', 'passwd', 'lmn_w_datetime', 'filesystem', 'auth_users', 'lmn_common', 'lmn_nextcloud', 'lmn_users', 'lmn_vdi_dashboard', 'lmn_vdi_administration', 'lmn_links', 'lmn_samba_dns', 'settings', 'lmn_websession', 'lmn_devices', 'lmn_linbo', 'lmn_groupmembership', 'lmn_auth', 'session_list', 'lmn_dhcp', 'lmn_quotas', 'lmn_landingpage', 'lmn_session', 'lmn_settings', 'lmn_linbo_sync']
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "core"
09.04.2021 18:21  [master  1230]          jadi.py:136   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider] (interface)
09.04.2021 18:21  [master  1230]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar] (service)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox] (service)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.api.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.config.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.main.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.push.Push] (service)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.push.PushSocket] (implementation of [aj.api.http.SocketEndpoint])
09.04.2021 18:21  [master  1230]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService] (service)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.tasks.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_cron"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_cron.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:70    DEBUG  Registering [aj.plugins.lmn_cron.manager.CronManager] (service)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_cron.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   lmn_crontab.__init__.py: lmn_crontab loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_docker"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_docker.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_docker.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   docker.__init__.py: docker loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_permissions"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_permissions.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_permissions.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_setup_wizard"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_setup_wizard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "ace"
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "plugins"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.plugins.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]        compat.py:19    DEBUG  Popen: ['/sbin/ldconfig', '-p']
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.plugins.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "dashboard"
09.04.2021 18:21  [master  1230]          jadi.py:136   DEBUG  Registering [aj.plugins.dashboard.api.Widget] (interface)
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.cpu.CPUWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.hostname.HostnameWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.loadavg.LoadAverageWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.memory.MemoryWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.uptime.UptimeWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "passwd"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.passwd.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_w_datetime"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_w_datetime.widget.RandomWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "filesystem"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "auth_users"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.auth_users.api.UsersAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.auth_users.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.auth_users.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_common"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_common.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_common.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_nextcloud"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_nextcloud.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_nextcloud.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:6     INFO   lmn_nextcloud.__init__.py: lmn_nextcloud loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_users"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_users.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_users.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]        compat.py:19    DEBUG  Popen: ['/sbin/ldconfig', '-p']
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_users.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_vdi_dashboard"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_dashboard.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_dashboard.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_dashboard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   lmn_vdi_dashboard.__init__.py: lmn_vdi_dashboard loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_vdi_administration"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_administration.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_administration.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_vdi_administration.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   lmn_vdi_administration.__init__.py: lmn_vdi_administration loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_links"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_links.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_links.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:6     INFO   lmn_links.__init__.py: lmn_links loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_samba_dns"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_samba_dns.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_samba_dns.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   samba_dns.__init__.py: samba_dns loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "settings"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.settings.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.settings.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_websession"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_websession.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_websession.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:6     INFO   lmn_websession.__init__.py: lmn_websession loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_devices"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_devices.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_devices.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_devices.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_linbo"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_groupmembership"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_groupmembership.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_groupmembership.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_groupmembership.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_auth"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_auth.api.LMAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_auth.api.UserLdapConfig] (implementation of [aj.config.UserConfigProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_auth.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "session_list"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.session_list.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.session_list.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_dhcp"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_dhcp.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_dhcp.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   lmn_dhcp.__init__.py: lmn_dhcp loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_quotas"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_quotas.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_quotas.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_quotas.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_landingpage"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_landingpage.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_landingpage.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]      __init__.py:5     INFO   lmn_landing.__init__.py: lmn_landing loaded
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_session"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_session.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_session.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_session.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_settings"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_settings.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_settings.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_settings.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:356   DEBUG  Importing plugin "lmn_linbo_sync"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo_sync.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo_sync.main.Permissions] (implementation of [aj.auth.PermissionProvider])
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.lmn_linbo_sync.views.Handler] (implementation of [aj.api.http.HttpPlugin])
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "core"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_cron"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_docker"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_permissions"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_setup_wizard"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "ace"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "plugins"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "dashboard"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "passwd"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_w_datetime"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "filesystem"
09.04.2021 18:21  [master  1230]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.widget.DiskWidget] (implementation of [aj.plugins.dashboard.api.Widget])
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "auth_users"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_common"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_nextcloud"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_users"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_vdi_dashboard"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_vdi_administration"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_links"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_samba_dns"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "settings"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_websession"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_devices"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_linbo"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_groupmembership"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_auth"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "session_list"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_dhcp"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_quotas"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_landingpage"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_session"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_settings"
09.04.2021 18:21  [master  1230]       plugins.py:366   DEBUG  Initializing plugin "lmn_linbo_sync"
09.04.2021 18:21  [master  1230]       plugins.py:353   INFO   Loaded 32 plugins
09.04.2021 18:21  [master  1230]          core.py:127   INFO   Binding to [0.0.0.0]:443
09.04.2021 18:21  [master  1230]          gipc.py:285   DEBUG  Invoke target `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7efe4f0b47f0>>` in child process.
09.04.2021 18:21  [master  1230]          gipc.py:509   DEBUG  SIGCHLD watcher for 1239 started.
09.04.2021 18:21  [...     1239]          gipc.py:322   DEBUG    _child start. target: `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7efe4f0b47f0>>`
09.04.2021 18:21  [master  1230]          gipc.py:303   DEBUG  Invalidate <_GIPCWriter_242760 fd: 7> in parent.
09.04.2021 18:21  [master  1230]          gipc.py:657   DEBUG  Invalidating <_GIPCWriter_242760 fd: 7> ...
09.04.2021 18:21  [master  1230]          gipc.py:303   DEBUG  Invalidate <_GIPCReader_c5aa61 fd: 8> in parent.
09.04.2021 18:21  [master  1230]          gipc.py:657   DEBUG  Invalidating <_GIPCReader_c5aa61 fd: 8> ...
09.04.2021 18:21  [master  1230]          gate.py:47    DEBUG  Started child process 1239
09.04.2021 18:21  [...     1239]          gipc.py:334   DEBUG    Delete current hub's threadpool.
09.04.2021 18:21  [...     1239]          gipc.py:343   DEBUG    Destroy hub and default loop.
09.04.2021 18:21  [...     1239]          gipc.py:348   DEBUG    Created new hub and default event loop.
09.04.2021 18:21  [...     1239]          gipc.py:355   DEBUG    Invalidate <_GIPCReader_862e66 fd: 4> in child.
09.04.2021 18:21  [master  1230]          core.py:181   INFO   SSL enabled
09.04.2021 18:21  [...     1239]          gipc.py:668   DEBUG    Legitimate <_GIPCReader_862e66 fd: 4> for current process.
09.04.2021 18:21  [...     1239]          gipc.py:657   DEBUG    Invalidating <_GIPCReader_862e66 fd: 4> ...
09.04.2021 18:21  [...     1239]          gipc.py:355   DEBUG    Invalidate <_GIPCWriter_4eafd8 fd: 9> in child.
09.04.2021 18:21  [...     1239]          gipc.py:668   DEBUG    Legitimate <_GIPCWriter_4eafd8 fd: 9> for current process.
09.04.2021 18:21  [...     1239]          gipc.py:657   DEBUG    Invalidating <_GIPCWriter_4eafd8 fd: 9> ...
09.04.2021 18:21  [...     1239]          gipc.py:668   DEBUG    Legitimate <_GIPCWriter_242760 fd: 7> for current process.
09.04.2021 18:21  [...     1239]          gipc.py:373   DEBUG    Handle `<_GIPCWriter_242760 fd: 7>` is now valid in child.
09.04.2021 18:21  [...     1239]          gipc.py:668   DEBUG    Legitimate <_GIPCReader_c5aa61 fd: 8> for current process.
09.04.2021 18:21  [...     1239]          gipc.py:373   DEBUG    Handle `<_GIPCReader_c5aa61 fd: 8>` is now valid in child.
09.04.2021 18:21  [rstrct  1239]          gate.py:121   INFO     New worker "restricted session" PID 1239, EUID 0, EGID 0
09.04.2021 18:21  [rstrct  1239]          gate.py:121   INFO     Worker 1239 is demoting to UID 65534 / GID 65534...
09.04.2021 18:21  [rstrct  1239]          gate.py:121   INFO     ...done, new EUID 65534 EGID 65534
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.016s    0.0 bytes   302 GET /
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /view/login/normal
09.04.2021 18:22  [...     1239]          main.py:73    WARN     Cannot build resources as restricted user nobody
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.006s      10.9 KB   200 GET /view/login/normal
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.vendor.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.027s       6.3 KB   200 GET /resources/all.vendor.css
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.024s      28.1 KB   200 GET /resources/all.css
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.vendor.js
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/core/resources/vendor/fontawesome/css/all.min.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.145s     645.3 KB   200 GET /resources/all.vendor.js
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/core/resources/vendor/fontawesome/css/v4-shims.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.158s      12.4 KB   200 GET /resources/core/resources/vendor/fontawesome/css/all.min.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.159s    0.0 bytes   304 GET /resources/core/resources/vendor/fontawesome/css/v4-shims.css
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/core/resources/vendor/pt-sans/styles/pt_sans.css
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.160s    0.0 bytes   304 GET /resources/core/resources/vendor/pt-sans/styles/pt_sans.css
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.init.js
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.152s  399.0 bytes   200 GET /resources/all.init.js
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.js
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.067s      63.4 KB   200 GET /resources/all.js
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/all.partials.js
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.116s      60.1 KB   200 GET /resources/all.partials.js
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_card_colored_darkblue_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.007s       9.1 KB   200 GET /resources/lmn_common/resources/img/course_card_colored_darkblue_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_card_colored_orange_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_people_colored_darkblue_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_class_colored_orange_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_class_colored_darkblue_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.009s    0.0 bytes   304 GET /resources/lmn_common/resources/img/course_card_colored_orange_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.008s    0.0 bytes   304 GET /resources/lmn_common/resources/img/course_people_colored_darkblue_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.005s    0.0 bytes   304 GET /resources/lmn_common/resources/img/course_class_colored_orange_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.004s    0.0 bytes   304 GET /resources/lmn_common/resources/img/course_class_colored_darkblue_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/lmn_common/resources/img/course_people_colored_orange_trans.png
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.004s    0.0 bytes   304 GET /resources/lmn_common/resources/img/course_people_colored_orange_trans.png
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/regular/PTS55F.woff
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.003s    0.0 bytes   304 GET /resources/core/resources/vendor/pt-sans/fonts/pt_sans/regular/PTS55F.woff
09.04.2021 18:22  [rstrct  1239]          gate.py:121   DEBUG                        ... GET /resources/core/resources/vendor/fontawesome/webfonts/fa-solid-900.woff2
09.04.2021 18:22  [master  1230]    middleware.py:250   DEBUG  0.003s    0.0 bytes   304 GET /resources/core/resources/vendor/fontawesome/webfonts/fa-solid-900.woff2
```

**Comment by dorianim** [comment]
By the way, what does the vdi plugin even do?

**Comment by kiarn** [comment]
> By the way, what does the vdi plugin even do?

It's a plugin from NI to manage virtual machines in proxmox. You can also move this directories from `/usr/lib/linuxmuster-webui/plugins` to another place and then restart the webui to test.

**Comment by dorianim** [comment]
So, I had t move the plugins `lmn_dhcp  lmn_samba_dns  lmn_vdi_administration  lmn_vdi_dashboard` away to get rid of the Module not available errors.
Now I get a different error though:
```
Error: [$injector:unpr] Unknown provider: devModeProvider <- devMode <- CoreRootController
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=devModeProvider%20%3C-%20devMode%20%3C-%20CoreRootController
minErr/<@https://10.9.0.1/resources/all.vendor.js:88:12
createInjector/providerCache.$injector<@https://10.9.0.1/resources/all.vendor.js:4583:19
getService@https://10.9.0.1/resources/all.vendor.js:4736:32
createInjector/protoInstanceInjector<@https://10.9.0.1/resources/all.vendor.js:4588:45
getService@https://10.9.0.1/resources/all.vendor.js:4736:32
injectionArgs@https://10.9.0.1/resources/all.vendor.js:4761:58
invoke@https://10.9.0.1/resources/all.vendor.js:4783:31
$controllerInit@https://10.9.0.1/resources/all.vendor.js:10612:34
nodeLinkFn@https://10.9.0.1/resources/all.vendor.js:9489:36
compositeLinkFn@https://10.9.0.1/resources/all.vendor.js:8830:23
compositeLinkFn@https://10.9.0.1/resources/all.vendor.js:8833:24
publicLinkFn@https://10.9.0.1/resources/all.lmn_dhcp  lmn_samba_dns  lmn_vdi_administration  lmn_vdi_dashboardvendor.js:8710:45
bootstrapApply/<@https://10.9.0.1/resources/all.vendor.js:1834:27
$eval@https://10.9.0.1/resources/all.vendor.js:18014:28
$apply@https://10.9.0.1/resources/all.vendor.js:18114:25
bootstrapApply@https://10.9.0.1/resources/all.vendor.js:1832:15
invoke@https://10.9.0.1/resources/all.vendor.js:4791:19
doBootstrap@https://10.9.0.1/resources/all.vendor.js:1830:14
bootstrap@https://10.9.0.1/resources/all.vendor.js:1850:12
__ngBootstrap@https://10.9.0.1/resources/all.js:656:13
window.ajentiBootstrap@https://10.9.0.1/resources/all.js:675:9
j@https://10.9.0.1/resources/all.vendor.js:17:26925
fireWith@https://10.9.0.1/resources/all.vendor.js:17:27738
ready@https://10.9.0.1/resources/all.vendor.js:17:29532
I@https://10.9.0.1/resources/all.vendor.js:17:29723
EventListener.handleEvent*n.ready.promise@https://10.9.0.1/resources/all.vendor.js:17:29834
@https://10.9.0.1/resources/all.vendor.js:17:29932
@https://10.9.0.1/resources/all.vendor.js:17:207
@https://10.9.0.1/resources/all.vendor.js:17:212
```

**Comment by dorianim** [comment]
Hi @kiarn 
Looks like it works fine! :)
Just one small proposal: As a Label, I would not use "Bypass start.conf" but rather "Bypass autostart"
